apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwc-share 
  namespace: default
  labels:
    storage: gwc-datadir 
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.36.0.11
    path: /data/geoserver_gwc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gwc-share  # The name of this Persistent Volume Claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi  # The size of the storage claim.
  storageClassName: ""
  selector:
    matchLabels:
      storage: "gwc-datadir"  # The volume must have this label with this value.